version: '3.1'

volumes:
  postgres-data:

services:
  postgres:
    image: pgautoupgrade/pgautoupgrade:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  admin:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: uvicorn mysaas.asgi:application --host 0.0.0.0 --reload
    depends_on:
      - postgres

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - '8001:8000'
    volumes:
      - ./backend:/app
    command: uvicorn mysaas.asgi:fastapp  --host 0.0.0.0 --reload
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
    image: frontend:latest
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: yarn dev
    depends_on:
      - api

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - admin
      - api
